<?php

namespace Container8dJexdm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2kssCz0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2kssCz0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2kssCz0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ApiController::createMessage' => ['privates', '.service_locator.nbxJ5_c', 'get_ServiceLocator_NbxJ5CService', true],
            'App\\Controller\\ApiController::getMessages' => ['privates', '.service_locator.sLkGFte', 'get_ServiceLocator_SLkGFteService', true],
            'App\\Controller\\DefaultController::index' => ['privates', '.service_locator.6WJWdiF', 'get_ServiceLocator_6WJWdiFService', true],
            'App\\Controller\\MessageController::delete' => ['privates', '.service_locator.eYMhV5n', 'get_ServiceLocator_EYMhV5nService', true],
            'App\\Controller\\MessageController::edit' => ['privates', '.service_locator.eYMhV5n', 'get_ServiceLocator_EYMhV5nService', true],
            'App\\Controller\\MessageController::index' => ['privates', '.service_locator.sLkGFte', 'get_ServiceLocator_SLkGFteService', true],
            'App\\Controller\\MessageController::map' => ['privates', '.service_locator.sLkGFte', 'get_ServiceLocator_SLkGFteService', true],
            'App\\Controller\\MessageController::new' => ['privates', '.service_locator.p7X0ugN', 'get_ServiceLocator_P7X0ugNService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ApiController:createMessage' => ['privates', '.service_locator.nbxJ5_c', 'get_ServiceLocator_NbxJ5CService', true],
            'App\\Controller\\ApiController:getMessages' => ['privates', '.service_locator.sLkGFte', 'get_ServiceLocator_SLkGFteService', true],
            'App\\Controller\\DefaultController:index' => ['privates', '.service_locator.6WJWdiF', 'get_ServiceLocator_6WJWdiFService', true],
            'App\\Controller\\MessageController:delete' => ['privates', '.service_locator.eYMhV5n', 'get_ServiceLocator_EYMhV5nService', true],
            'App\\Controller\\MessageController:edit' => ['privates', '.service_locator.eYMhV5n', 'get_ServiceLocator_EYMhV5nService', true],
            'App\\Controller\\MessageController:index' => ['privates', '.service_locator.sLkGFte', 'get_ServiceLocator_SLkGFteService', true],
            'App\\Controller\\MessageController:map' => ['privates', '.service_locator.sLkGFte', 'get_ServiceLocator_SLkGFteService', true],
            'App\\Controller\\MessageController:new' => ['privates', '.service_locator.p7X0ugN', 'get_ServiceLocator_P7X0ugNService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ApiController::createMessage' => '?',
            'App\\Controller\\ApiController::getMessages' => '?',
            'App\\Controller\\DefaultController::index' => '?',
            'App\\Controller\\MessageController::delete' => '?',
            'App\\Controller\\MessageController::edit' => '?',
            'App\\Controller\\MessageController::index' => '?',
            'App\\Controller\\MessageController::map' => '?',
            'App\\Controller\\MessageController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ApiController:createMessage' => '?',
            'App\\Controller\\ApiController:getMessages' => '?',
            'App\\Controller\\DefaultController:index' => '?',
            'App\\Controller\\MessageController:delete' => '?',
            'App\\Controller\\MessageController:edit' => '?',
            'App\\Controller\\MessageController:index' => '?',
            'App\\Controller\\MessageController:map' => '?',
            'App\\Controller\\MessageController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
