<?php

namespace Container8dJexdm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P7X0ugNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p7X0ugN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p7X0ugN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'api' => ['privates', 'App\\Services\\AddressAPIService', 'getAddressAPIServiceService', true],
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
        ], [
            'api' => 'App\\Services\\AddressAPIService',
            'messageRepository' => 'App\\Repository\\MessageRepository',
        ]);
    }
}
