<?php

namespace Container8dJexdm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressAPIServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\AddressAPIService' shared autowired service.
     *
     * @return \App\Services\AddressAPIService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/AddressAPIService.php';

        return $container->privates['App\\Services\\AddressAPIService'] = new \App\Services\AddressAPIService();
    }
}
