<?php

namespace Container8dJexdm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKernel_Listener_PrefixService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'kernel.listener.prefix' shared autowired service.
     *
     * @return \App\EventListener\TablePrefixEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/TablePrefixEventListener.php';

        $container->privates['kernel.listener.prefix'] = $instance = new \App\EventListener\TablePrefixEventListener();

        $instance->setConfig($container->parameters['table_prefix']);

        return $instance;
    }
}
