<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8dJexdm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8dJexdm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8dJexdm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8dJexdm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8dJexdm\App_KernelDevDebugContainer([
    'container.build_hash' => '8dJexdm',
    'container.build_id' => '881c9e43',
    'container.build_time' => 1678866305,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8dJexdm');
